init: start commit
Meamnim/fitness-general-api pull request #9
Opened 2022-01-02 11:31 UTC by GalOren33

entities and relation

2022-01-02 14:39 UTC, davidtrainers requested changes

2022-01-02 14:39 UTC, davidtrainers commented on src/entities/allergies.ts
> +	@Column({})
add text type

2022-01-02 14:39 UTC, davidtrainers commented on src/entities/allergies.ts
> +export class allergies {
Capital letter Allergies

2022-01-03 13:11 UTC, GalOren33 commented on src/entities/allergies.ts
> +export class allergies {
done for all

2022-01-03 13:11 UTC, GalOren33 commented on src/entities/allergies.ts
> +	@Column({})
done

2022-01-03 13:12 UTC, GalOren33 commented on src/entities/allergies.ts
> +	@Column({ nullable: false })
done

2022-01-03 17:17 UTC, davidtrainers requested changes

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/measurements..entity.ts
> +	@Column()
add numeric type

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/measurements..entity.ts
> +	@Column()
add numeric type

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/planes.entity.ts
> +import {
change file name to plans

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/planes.entity.ts
> +	@Column()
Where is the reference to the forces table

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/results.entity.ts
> +	component: Components[];
Why component and also event_type_comp_id

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/scores.entity.ts
> +	@Column()
add numeric type

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/scores.entity.ts
> +	@Column({ nullable: false })
add numeric type

2022-01-03 17:17 UTC, davidtrainers commented on src/entities/weeks.entity.ts
> +
Change to string and add text type

2022-01-04 14:37 UTC, davidtrainers requested changes

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/allergies.entity.ts
> +	participant_id: Participants;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/categories.entity.ts
> +	parent_id: Categories;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/event_type.entity.ts
> +	event_category_id: EventType;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/event_type_comp_con.entity.ts
> +	event_type_id: Components;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/events.entity.ts
> +	week_id: Weeks;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/events.entity.ts
> +	force_id: Forces;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/forces.entity.ts
> +	parent_id: Forces;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/measurements.entity.ts
> +	participant_id: Participants;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/participants.entity.ts
> +	user_id: Users;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/restrections.entity.ts
> +	participant_id: Participants;
remove id

2022-01-04 14:37 UTC, davidtrainers commented on src/utils/logger.ts
> +    // // error log setting
remove

2022-01-04 14:37 UTC, davidtrainers commented on src/routes/index.route.ts
> +import { createConnection, getRepository } from 'typeorm';
remove three imports

2022-01-04 14:37 UTC, davidtrainers commented on src/routes/events.route.ts
> +  //   public usersController = new eventsController();
remove

2022-01-04 14:37 UTC, davidtrainers commented on src/entities/allergies.entity.ts
> +	@Column({ nullable: false })
add default

2022-01-04 21:49 UTC, davidtrainers approved these changes

2022-01-04 22:07 UTC, merged